name: Unit Tests
on:
  push:
    branches:
      # A test branch for seeing if your tests will pass in your personal fork
      - test_me_github
  pull_request:
    branches:
      - main
      - master
jobs:
  docker-rspec:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7
          - 2.6
          - 2.5
          - 2.4
        docker_version:
          - 5:19.03.8~3-0~ubuntu-bionic
          - 5:18.09.9~3-0~ubuntu-bionic
          - 18.06.3~ce~3-0~ubuntu
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: install bundler
        run: |
          gem install bundler -v '~> 1.17.3'
          bundle update
      - name: install docker
        env:
          DOCKER_VERSION: ${{ matrix.docker_version }}
        run: sudo ./script/install_docker.sh ${DOCKER_VERSION} ${DOCKER_CE}
      - name: spec tests
        run: bundle exec rake

  podman-rspec:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7
          - 2.6
          - 2.5
          - 2.4
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: install bundler
        run: |
          gem install bundler -v '~> 1.17.3'
          bundle update
      - name: install podman
        run: sudo ./script/install_podman.sh
      - name: spec tests
        run: bundle exec rake
